services:
  web:
    build: .
    volumes:
      - ./music:/app/music
    environment:
      CARDAMON_DIRECTORIES_MUSIC: "music/"
      CARDAMON_DIRECTORIES_OUTPUT: "output/"
      CARDAMON_DIRECTORIES_TEMPLATES: "templates/"
      CARDAMON_THEME_TITLE: "cardamon's house"
      CARDAMON_SERVER_PORT: "80"
      CARDAMON_SERVER_DOMAIN: "0.0.0.0"
      CARDAMON_SERVER_ROOT_PATH: "/~cardamon"


